version: 2

jobs:
  build:
    working_directory: ~/wikiespirita
    docker:
      - image: node:9.11
        environment:
          TZ: "/usr/share/zoneinfo/America/Sao_Paulo"
          LANG: pt_BR.UTF-8
          LC_ALL: C.UTF-8
          LANGUAGE: pt_BR.UTF-8
          DEPLOY_BRANCH: master

    steps:
      - checkout

#      - add_ssh_keys:
#          fingerprints:
#            - "32:ce:f6:c9:dc:51:55:8b:8b:8b:e1:c1:43:75:f0:54"
#            - "fc:f9:33:58:df:b0:90:d5:0c:0e:71:53:d0:26:de:0a"

      #### Node dependencies ####
      - restore_cache:
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-

      - run:
          name: Install Node dependencies
          command: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      #### Node dependencies end ####

      - run:
          name: Deploy master branch to gh-pages
          command: |
            if [ "${CIRCLE_BRANCH}" = "${DEPLOY_BRANCH}" ]; then
              chmod +x deploy.sh
              ./deploy.sh
            fi